controllers/about.py
from flask import Blueprint,render_template
about_page = Blueprint( "about_page",__name__ )

@about_page.route("/<string:lan>")
def about(lan):
    return render_template( "about.html",lan=lan )

controllers/shop.py
import math
from os import path
from werkzeug.utils import secure_filename
from libs import UserService
from libs.DataHelper import getCurrentTime
from libs.Helper import ops_render, ops_renderErrJSON, ops_renderJSON
from models import *
from datetime import datetime
from models.user import *
from models.shop import *
from flask import Blueprint, render_template, redirect, url_for, request, send_from_directory, flash

shop_page = Blueprint("shop_page", __name__)


def sortAndSelect(order, category):
    if order == 1:
        product = getAllShopByTime()
    elif order == 2:
        product = getAllShopByAZ()
    elif order == 3:
        product = getAllShopByZA()
    elif order == 4:
        product = getAllShopByPriceUp()
    elif order == 5:
        product = getAllShopByPriceDown()
    else:
        product = getAllShopByTime()
    selected = []
    if category == "all":
        for i in product:
            selected.append(i)
    else:
        for i in product:
            if i.category == category:
                selected.append(i)
    return selected


@shop_page.route("/shop_full/<string:lan>/<string:category>/<int:order>/<int:page>", methods=['POST', 'GET'])
def shop_full(lan, category, order, page):
    if request.method == 'GET':
        fullPath = request.full_path
        pathList = fullPath.split(sep="/")
        category = pathList[4]
        order = pathList[5]
        product = sortAndSelect(order, category)
        categories = getAllCategories()
        categories2 = getAllCategories2()
        allProduct = getAllShop()
        allNum = len(allProduct)
        selectedNum = len(product)
        pageNum = math.ceil(selectedNum / 8)
        if 'username' in session:
            carts = getAllCarts(session['username'])
            return render_template("shop-list.html", carts=carts, product=product, categories=categories,
                                   categories2=categories2, allNum=allNum,
                                   pageNum=pageNum, page=page, order=order, category=category, selectedNum=selectedNum,
                                   lan=lan)
        return render_template("shop-list.html", product=product, categories=categories, categories2=categories2,
                               allNum=allNum, pageNum=pageNum,
                               page=page, order=order, category=category, selectedNum=selectedNum, lan=lan)
    if request.method == 'POST':
        fullPath = request.full_path
        pathList = fullPath.split(sep="/")
        category = pathList[4]
        order = pathList[5]
        product = sortAndSelect(order, category)
        categories = getAllCategories()
        categories2 = getAllCategories2()
        allProduct = getAllShop()
        allNum = len(allProduct)
        selectedNum = len(product)
        pageNum = math.ceil(selectedNum / 8)
        if 'username' in session:
            carts = getAllCarts(session['username'])
            return render_template("shop-list.html", carts=carts, product=product, categories=categories,
                                   categories2=categories2, allNum=allNum,
                                   pageNum=pageNum, page=page, order=order, category=category, selectedNum=selectedNum,
                                   lan=lan)
        return render_template("shop-list.html", product=product, categories=categories, allNum=allNum, pageNum=pageNum,
                               page=page, order=order, category=category, categories2=categories2,
                               selectedNum=selectedNum, lan=lan)


@shop_page.route("/single_product/<int:id>/<string:lan>", methods=['GET', 'POST'])
def single_product(id, lan):
    ID = findProductID(id)
    products = getAllShopByTime()
    reviews = getAllProductReviews(id)
    if request.method == "GET":
        if 'username' in session:
            username = session['username']
            carts = getAllCarts(username)
            isTrue = isExisted(username, ID.productName)
            order = isExistedOrder(username, ID.productName)
            return render_template('single-product.html', carts=carts, ID=ID, id=id - 1, products=products[0:6],
                                   isTrue=isTrue, order=order, reviews=reviews, reviewNum=len(reviews), lan=lan)
        return render_template('single-product.html', ID=ID, id=id - 1, products=products[0:4], reviews=reviews,
                               reviewNum=len(reviews), lan=lan)



@shop_page.route("/review/<int:id>/<string:lan>",methods=['GET','POST'])
def review(id,lan):
    ID = findProductID(id)
    products = getAllShopByTime()
    reviews = getAllProductReviews(id)
    if request.method == 'POST':
        if 'username' in session:
            productReviews = request.form.get('review', None)
            score = request.form.get('score',None)
            print(productReviews)
            reviews = ProductReviews(id, session['username'], productReviews, score)
            reviews.addProductReviews()
            return redirect(url_for('shop_page.single_product', id=id, lan=lan))
        return render_template('single-product.html', ID=ID, products=products[0:4], reviews=reviews,
                               reviewNum=len(reviews), lan=lan)
    if request.method == "GET":
        if 'username' in session:
            username = session['username']
            carts = getAllCarts(username)
            isTrue = isExisted(username, ID.productName)
            order = isExistedOrder(username, ID.productName)
            return render_template('newReview.html', carts=carts, ID=ID, id=id - 1, products=products[0:6],
                                   isTrue=isTrue, order=order, reviews=reviews, reviewNum=len(reviews), lan=lan)
        return render_template('single-product.html', ID=ID, id=id - 1, products=products[0:4], reviews=reviews,
                               reviewNum=len(reviews), lan=lan)



@shop_page.route('/cart/<string:lan>')
def carts(lan):
    if 'username' in session:
        carts = getAllCarts(session['username'])
        return render_template("cart.html", carts=carts, totalPrices=Prices(carts), lan=lan)
    flash("Please login")
    return redirect(url_for('member_page.login'))


def Prices(carts):
    a = []
    for p in carts:
        a.append(p.price)
    totalPrices = sum([float(i) for i in a])
    return totalPrices


@shop_page.route('/checkout/<string:lan>')
def checkout(lan):
    # if request.method == 'POST':
    #     addressusername = request.form.get('username')
    #     userPhone = request.form.get('userPhone')
    #     town = request.form.get('town')
    #     detailedAddress = request.form.get('detailedAddress')
    #     print(detailedAddress)
    #     postCode = request.form.get('postCode')
    #     email = request.form.get('email')
    #     note = request.form.get('note')
    #     user_address = Address(1, addressusername, userPhone, town, detailedAddress, postCode, email, note)
    #     user_address.addAddress()
    #     return redirect(url_for('shop_page.checkout', lan=lan))

    # if request.method == 'GET':
    if 'username' in session:
        user = findUser(session['username'])
        address = findAddress(session['username'])
        carts = getAllCarts(session['username'])
        return render_template('checkout.html', lan=lan, carts=carts, totalPrices=Prices(carts),
                               username=session['username'], address=address, user=user, price=Prices(carts))
    flash("Please login")
    return redirect(url_for('member_page.login'))


@shop_page.route('/order/<string:lan>')
def orders(lan):
    if 'username' in session:
        carts = getAllCarts(session['username'])
        submitOrder(session['username'])
        for cart in carts:
            delCart(cart.id)
        if lan == "e":
            return redirect(url_for('index_page.index'))
        elif lan == "c":
            return redirect(url_for('index_page.index2'))


@shop_page.route('/pay/<string:lan>')
def pay(lan):
    return render_template('pay.html',lan=lan)


@shop_page.route('/addcs/<int:idsss>/<string:lan>', methods=['GET', 'POST'])
def addcartssss(idsss,lan):
    if 'username' in session:
        name = session['username']
        ID = findProductID(idsss)
        usercart = Cart(idsss, name, ID.productName, ID.productName2, ID.price, ID.images, ID.description, 1)
        usercart.addCart()
        return redirect(url_for('shop_page.single_product',lan=lan, id=ID.id))
    flash("Please login")
    return redirect(url_for('member_page.login'))


@shop_page.route('delcart/<int:id>')
def delcart(id):
    if 'username' in session:
        delCart(id)
        return redirect(url_for('shop_page.carts'))
    return redirect(url_for('shop_page.carts'))

controllers/staff.py
import os
from datetime import datetime
from flask import Flask, request, make_response, render_template, redirect, url_for, app, Blueprint
from werkzeug.utils import secure_filename
from os import path

from models.shop import *
from models.user import *

staff_page = Blueprint("staff_page", __name__)

base_path = path.abspath(path.dirname(""))
upload_path = path.join(base_path, 'static\\uploads\\')

ALLOWED_EXTENSIONS = ['.jpg', '.png', '.gif']


def allowed_file(filename):
    _, ext = os.path.splitext(filename)
    return ext.lower() in ALLOWED_EXTENSIONS


def checkAdmin(username):
    adminList = getAdmin()
    if username in adminList:
        return True
    else:
        return False


@staff_page.route('/<string:lan>', methods=['GET'])
def warn(lan):
    return render_template('error.html', lan=lan)


@staff_page.route('/delete-product/<int:id>/<string:lan>')
def delete_product(id, lan):
    delProduct(id)
    return redirect(url_for('staff_page.show_product', lan=lan))


@staff_page.route('/new-product/<string:lan>', methods=['GET', 'POST'])
def new_product(lan):
    if 'username' in session:
        username = findUser(session['username'])
        ifAdmin = checkAdmin(username)
        if ifAdmin:
            if request.method == 'GET':
                return render_template('newProduct.html', lan=lan)
            if request.method == 'POST':
                productName = request.form.get('productName', None)
                productName2 = request.form.get('productName2', None)
                price = request.form.get('price', None)
                description = request.form.get('description', None)
                description2 = request.form.get('description2', None)
                category = request.form.get('category', None)
                category2 = request.form.get('category2', None)
                img_path = None
                image = request.files.get('image')
                if allowed_file(image.filename):
                    img_path = datetime.now().strftime('%Y%m%d%H%M%f') + os.path.splitext(image.filename)[1]
                    image.save(os.path.join(upload_path, img_path))
                images = "/static/uploads/" + str(img_path)
                product = Product(productName=productName, productName2=productName2, price=price, images=images,
                                  description=description, description2=description2, score=None, category=category,
                                  category2=category2)
                product.addShop()
                return redirect(url_for('staff_page.show_product', lan=lan))
        else:
            return redirect(url_for('staff_page.warn', lan=lan))
    return redirect(url_for('member_page.login', lan=lan))


@staff_page.route('/show-product/<string:lan>')
def show_product(lan):
    if 'username' in session:
        username = findUser(session['username'])
        ifAdmin = checkAdmin(username)
        if ifAdmin:
            if request.method == 'GET':
                products = getAllShop()
                return render_template('delProduct.html', products=products, lan=lan)
        else:
            return redirect(url_for('staff_page.warn', lan=lan))
    return redirect(url_for('member_page.login', lan=lan))


@staff_page.route('/edit-product/<int:id>/<string:lan>')
def edit_product(id, lan):
    if 'username' in session:
        username = findUser(session['username'])
        ifAdmin = checkAdmin(username)
        if ifAdmin:
            product = findProduct(id)
            return render_template('editProduct.html', product=product, lan=lan)
        else:
            return redirect(url_for('staff_page.warn', lan=lan))
    return redirect(url_for('member_page.login', lan=lan))


@staff_page.route('/modify-product/<int:id>/<string:lan>', methods=['GET', 'POST'])
def modify_product(id, lan):
    if request.method == 'POST':
        productName = request.form.get('productName', None)
        productName2 = request.form.get('productName2', None)
        price = request.form.get('price', None)
        description = request.form.get('description', None)
        description2 = request.form.get('description2', None)
        category = request.form.get('category', None)
        category2 = request.form.get('category2', None)
        img_path = None
        image = request.files.get('image')
        if allowed_file(image.filename):
            img_path = datetime.now().strftime('%Y%m%d%H%M%f') + os.path.splitext(image.filename)[1]
            image.save(os.path.join(upload_path, img_path))
        images = "/static/uploads/" + str(img_path)
        modifyProduct(id, productName, productName2, price, images, description, description2, None, category,
                      category2)
        return redirect(url_for('staff_page.show_product', lan=lan))


@staff_page.route('/show-order/<string:lan>')
def show_order(lan):
    if 'username' in session:
        username = findUser(session['username'])
        ifAdmin = checkAdmin(username)
        if ifAdmin:
            if request.method == 'GET':
                orders = getOrderList()
                return render_template('delOrder.html', lan=lan, orders=orders)
        else:
            return redirect(url_for('staff_page.warn', lan=lan))
    return redirect(url_for('member_page.login', lan=lan))


@staff_page.route('/delete-order/<int:id>/<string:lan>')
def delete_order(id, lan):
    delOrder(id)
    return redirect(url_for('staff_page.show_order', lan=lan))

templates/delOrder.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if lan == "e" %}
        <title>Order List</title>
    {% elif lan == "c" %}
        <title>订单列表</title>
    {% endif %}
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/js/admin/jquery-1.11.0.js"></script>
    <script src="/static/js/admin/bootstrap.js"></script>
</head>
<body>
<div align="center">
    {% if lan == "e" %}
        <h1>Order List</h1>
    {% elif lan == "c" %}
        <h1>订单列表</h1>
    {% endif %}
    <table class="table table-hover table-striped" id="wi" align="center">
        {% if lan == "e" %}
            <tr>
                <th>id</th>
                <th>Username</th>
                <th>Product Name</th>
                <th>Price</th>
                <th>Dispatched</th>
                <th>Received</th>
                <th>Delete</th>
            </tr>
        {% elif lan == "c" %}
            <tr>
                <th>id</th>
                <th>用户名</th>
                <th>商品名</th>
                <th>价格</th>
                <th>是否发货</th>
                <th>是否收货</th>
                <th>删除</th>
            </tr>
        {% endif %}
        {% if orders %}
            {% for order in orders %}
                {% if lan == "e" %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.username }}</td>
                        <td>{{ order.productName }}</td>
                        <td>{{ order.price }}</td>
                        {% if order.dispatched == 0 %}
                            <td>×</td>
                        {% else %}
                            <td>√</td>
                        {% endif %}
                        {% if order.received == 0 %}
                            <td>×</td>
                        {% else %}
                            <td>√</td>
                        {% endif %}
                        <td><a href="{{ url_for('staff_page.delete_order',lan=lan,id=order.id) }}">Delete</a></td>
                    </tr>
                {% elif lan == "c" %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.username }}</td>
                        <td>{{ order.productName2 }}</td>
                        <td>{{ order.price }}</td>
                        {% if order.dispatched == 0 %}
                            <td>×</td>
                        {% else %}
                            <td>√</td>
                        {% endif %}
                        {% if order.received == 0 %}
                            <td>×</td>
                        {% else %}
                            <td>√</td>
                        {% endif %}
                        <td><a href="{{ url_for('staff_page.delete_order',lan=lan,id=order.id) }}">删除</a></td>
                    </tr>
                {% endif %}
            {% endfor %}
        {% endif %}
    </table>
</div>
</body>
</html>
<style>
    #wi {
        width: 80%;
    }
</style>

templates/editAddress.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if lan == "e" %}
        <title>Edit Address</title>
    {% elif lan == "c" %}
        <title>编辑地址</title>
    {% endif %}
</head>
<body>
<div id="product" align="center">
    {% if lan == "e" %}
        <h1>Modify Address</h1>
    {% elif lan == "c" %}
        <h1>修改地址</h1>
    {% endif %}
    <div id="management">
        {% if lan == "e" %}
            <form action="{{ url_for('member_page.modify_address',username=address.username,lan=lan) }}" method="post"
                  enctype="multipart/form-data">
                <h4>Address Name</h4>
                <input type="text" name="addressName" value="{{ address.addressName if address else '' }}"
                       placeholder="Address Name" id="addressName">
                <h4>Phone</h4>
                <input type="text" name="phone" value="{{ address.userPhone if address else '' }}" placeholder="phone"
                       id="phone">
                <h4>Country</h4>
                <input type="text" name="country" value="{{ address.country if address else '' }}" placeholder="country"
                       id="country">
                <h4>Town</h4>
                <input type="text" name="town" value="{{ address.town if address else '' }}" placeholder="town"
                       id="town">
                <h4>Detail</h4>
                <input type="text" name="detail" value="{{ address.detail if address else '' }}" placeholder="detail"
                       id="detail">
                <h4>Post Code</h4>
                <input type="text" name="postCode" value="{{ address.postCode if address else '' }}"
                       placeholder="postCode"
                       id="postCode">
                <a href="{{ url_for('member_page.modify_address',username=address.username,lan=lan) }}"><input type="submit"
                                                                                                       value="Submit"
                                                                                                       id="sb"></a>
            </form>
        {% elif lan == "c" %}
            <form action="{{ url_for('member_page.modify_address',username=address.username,lan=lan) }}" method="post"
                  enctype="multipart/form-data">
                <h4>地址名称</h4>
                <input type="text" name="addressName" value="{{ address.addressName if address else '' }}"
                       placeholder="地址名称" id="addressName">
                <h4>手机号</h4>
                <input type="text" name="phone" value="{{ address.userPhone if address else '' }}" placeholder="手机号"
                       id="phone">
                <h4>国家</h4>
                <input type="text" name="country" value="{{ address.country if address else '' }}" placeholder="国家"
                       id="country">
                <h4>城市</h4>
                <input type="text" name="town" value="{{ address.town if address else '' }}" placeholder="城市"
                       id="town">
                <h4>详细地址</h4>
                <input type="text" name="detail" value="{{ address.detail if address else '' }}" placeholder="详细地址"
                       id="detail">
                <h4>邮政编码</h4>
                <input type="text" name="postCode" value="{{ address.postCode if address else '' }}"
                       placeholder="邮政编码"
                       id="postCode">
                <a href="{{ url_for('member_page.modify_address',username=address.username,lan=lan) }}"><input type="submit"
                                                                                                       value="提交"
                                                                                                       id="sb"></a>
            </form>
        {% endif %}
    </div>
    <style>
        #product {
            width: 60%;
            /*height: 730px;*/
            margin: 0 auto;
        }

        #product h1 {
            margin-top: 15%;
        }

        #management {
            margin-top: 5%;
            text-align: left;
        }

        #management h4 {
            margin-top: 3%;
        }

        #productName, #price {
            width: 800px;
            height: 50px;
        }

        .fileClassInput {
            width: 800px;
            height: 50px;
            /*border: 1px solid green;*/
            margin-top: 5px;
        }

        .fileClassInput:hover {
            border: 1px solid green;
        }

        #description {
            width: 800px;
            height: 220px;
            resize: none;
        }

        #sb {
            width: 800px;
            height: 50px;
            color: white;
            border: none;
            margin-top: 10px;
            background-color: #1c7430;
        }
    </style>
</div>
</body>
</html>

{#<script>#}
{#    Toast('Successfully Edited', 2000);#}
{##}
{##}
{#    function Toast(msg, duration) {#}
{#        duration = isNaN(duration) ? 3000 : duration;#}
{#        var m = document.createElement('div');#}
{#        m.innerHTML = msg;#}
{#        m.style.cssText = "width:10%; min-width:125px; background:black; opacity:0.5; height:50px; color:#fff; line-height:50px; text-align:center; border-radius:5px; position:fixed; top:50%; left:45%; z-index:999999; font-weight:bold;";#}
{#        document.body.appendChild(m);#}
{#        setTimeout(function () {#}
{#            var d = 0.5;#}
{#            m.style.webkitTransition = '-webkit-transform ' + d + 's ease-in, opacity ' + d + 's ease-in';#}
{#            m.style.opacity = '0';#}
{#            setTimeout(function () {#}
{#                document.body.removeChild(m)#}
{#            }, d * 1000);#}
{#        }, duration);#}
{#    }#}
{#</script>#}

templates/error.html
{% extends "test/shop_base.html" %}
{% block title %}
    {% if lan == "e" %}
        Error
    {% elif lan == "c" %}
        错误
    {% endif %}
{% endblock %}
{% block content %}
    <!--Error 404 Area Start-->
    <div class="error-404-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="error-wrapper text-center">
                        {% if lan == "e" %}
                            <div class="error-text">
                                <h1>Error</h1>
                                <h2>You are not permitted to access this page. </h2>
                                <p>Sorry but only staffs can access this page. </p>
                            </div>
                        {% elif lan == "c" %}
                            <div class="error-text">
                                <h1>错误</h1>
                                <h2>您没有权限访问该页面。 </h2>
                                <p>很抱歉，该页面仅工作人员可访问。 </p>
                            </div>
                        {% endif %}
                        <div class="error-button">
                            {% if lan == "e" %}
                                <a href="{{ url_for("index_page.index") }}">Back to home page</a>
                            {% elif lan == "c" %}
                                <a href="{{ url_for("index_page.index2") }}">返回首页</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--Error 404 Area End-->
{% endblock %}

templates/pay.html
{% block content %}
    <div align="center">
        {% if lan == "e" %}
            <h1 style="margin-top: 10%">QR Code for Payment</h1>
        {% elif lan == "c" %}
            <h1 style="margin-top: 10%">支付二维码</h1>
        {% endif %}
        <div>
            <img src="{{ url_for('static',filename='img/zfb.jpg') }}" alt="" width="23%" >
        </div>
        <li><a href="{{ url_for('shop_page.orders',lan=lan) }}">Submit Order</a></li>
    </div>
{% endblock %}